# Generated by Django 3.1.2 on 2021-03-18 05:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201101_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Konten',
        ),
    ]
