# Generated by Django 3.1.2 on 2021-03-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210318_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('isi', models.TextField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=True)),
                ('konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seluruh_komentar', to='blog.konten')),
            ],
            options={
                'ordering': ('dibuat',),
            },
        ),
    ]
